# Generated by Django 2.0.9 on 2018-11-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utkani',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sezona', models.CharField(max_length=100)),
                ('tym', models.CharField(max_length=100)),
                ('soutez', models.CharField(max_length=200)),
                ('kolo', models.CharField(max_length=50)),
                ('datum', models.DateTimeField(verbose_name='datum utkání')),
                ('souperi', models.CharField(max_length=300)),
                ('vysledek', models.CharField(max_length=50)),
                ('sestava', models.CharField(max_length=700)),
                ('nahradnici', models.CharField(max_length=500)),
                ('goly', models.CharField(max_length=300)),
            ],
        ),
    ]
