# Generated by Django 2.0.9 on 2018-12-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vysledky_s', '0002_auto_20181127_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabulka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poradi', models.CharField(max_length=100)),
                ('tymy', models.CharField(max_length=500)),
                ('pocet_utkani', models.CharField(max_length=100)),
                ('pocet_vyher', models.CharField(max_length=100)),
                ('pocet_remiz', models.CharField(max_length=100)),
                ('pocet_proher', models.CharField(max_length=100)),
                ('skore', models.CharField(max_length=200)),
                ('body', models.CharField(max_length=150)),
                ('tym', models.CharField(max_length=50)),
                ('kolo', models.CharField(max_length=10)),
            ],
        ),
    ]
