# Generated by Django 2.0.9 on 2019-03-14 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vysledky_s', '0007_auto_20190314_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utkani',
            name='koment',
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
