# Generated by Django 2.0.13 on 2019-07-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vysledky_s', '0008_auto_20190314_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabulka',
            name='sezona',
            field=models.CharField(default='2018-2019', max_length=100),
        ),
    ]
