# Generated by Django 2.0.13 on 2019-09-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vysledky_s', '0009_tabulka_sezona'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rozpis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tym', models.CharField(max_length=100)),
                ('soutez', models.CharField(max_length=200)),
                ('kolo', models.CharField(max_length=50)),
                ('datum', models.CharField(max_length=70)),
                ('cas', models.CharField(max_length=50)),
                ('souper', models.CharField(max_length=300)),
                ('hriste', models.CharField(max_length=100)),
                ('doma_venku', models.CharField(max_length=20)),
            ],
        ),
    ]
